---
- name: Update Neovim Configuration Only  
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Get current username
      command: whoami
      register: username_result
      changed_when: false

    - name: Get user's home directory
      shell: 'echo $HOME'
      register: user_home
      changed_when: false

    - name: Copy Neovim plugin configuration files
      copy:
        src: "roles/neovim/files/lua/plugins/{{ item }}"
        dest: "{{ user_home.stdout }}/.config/nvim/lua/plugins/{{ item }}"
        force: yes
      with_items:
        - "init.lua"

    - name: Copy Neovim core configuration files
      copy:
        src: "roles/neovim/files/lua/core/{{ item }}"
        dest: "{{ user_home.stdout }}/.config/nvim/lua/core/{{ item }}"
        force: yes
      with_items:
        - "keymaps.lua"
        - "options.lua"
        - "init.lua"
        - "autocmds.lua"

    - name: Copy Neovim snippet files
      copy:
        src: "roles/neovim/files/snippets/{{ item }}"
        dest: "{{ user_home.stdout }}/.config/nvim/snippets/{{ item }}"
        force: yes
      with_items:
        - "php.json"
        - "markdown.json"
        - "javascript.json"
        - "typescript.json"
        - "typescriptreact.json"