---
- name: Include platform-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages (Ubuntu)
  apt:
    name: "{{ software_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Homebrew packages (macOS)
  homebrew:
    name: "{{ software_packages }}"
    state: present
    update_homebrew: yes
  when: ansible_os_family == "Darwin"
